# https://taskfile.dev

version: '3'

vars:
  REPOSITORY: ghcr.io/adrianliechti/wingman-realtime-proxy

tasks:
  publish:
    cmds:
      - docker buildx build . --push --platform linux/amd64,linux/arm64 --tag {{.REPOSITORY}}
